"""Add item_status column to LostItem table

Revision ID: bc77cac7a0e7
Revises: 93df0f7351c6
Create Date: 2023-06-15 02:33:24.037455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77cac7a0e7'
down_revision = '93df0f7351c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', sa.String(length=10), nullable=False))

    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.drop_column('item_status')

    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('item_status')

    # ### end Alembic commands ###
